org.gradle.jvmargs=-Xmx1024m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=1

android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
android.suppressUnsupportedCompileSdk=35

kotlin.code.style=official

systemProp.java.net.preferIPv4Stack=true
systemProp.java.net.preferIPv6Addresses=false
systemProp.org.gradle.internal.http.connectionTimeout=600000
systemProp.org.gradle.internal.http.socketTimeout=600000
